CREATE TABLE V_DEPARTMENTS (
    DEPARTMENT_ID NUMBER,
    DEPARTMENT_NAME VARCHAR2(100)
);

CREATE TABLE V_EMPLOYEES (
    EMP_ID NUMBER,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    EMAIL VARCHAR2(100),
    SALARY NUMBER,
    DEPARTMENT_ID NUMBER,
);

