SELECT
NVL(SCH.VENDOR_NAME,(SELECT NAME FROM APPS.HR_ALL_ORGANIZATION_UNITS WHERE 1=1 AND ORGANIZATION_ID = SCH.SOURCE_ORGANIZATION_ID)) AS VENDOR_NAME,
-- SCH.VENDOR_NAME,
SCH.ITEM,
SCH.DESCR,
SCH.PLAN_NAME,
SCH.FULL_LEAD_TIME,
SCH.ORDER_TYPE,
SCH.ORG_CODE,
SCH.ORG_NAME,
SCH.PRESENT_WK,
SCH.PRESENT_WK_1,
SCH.PRESENT_WK_2,
SCH.PRESENT_WK_3,
SCH.PRESENT_WK_4,
SCH.PRESENT_WK_5,
SCH.PRESENT_WK_6,
SCH.PRESENT_WK_7,
SCH.PRESENT_WK_8,
SCH.PRESENT_WK_9,
SCH.JAN,
SCH.FEB,
SCH.MAR,
SCH.APR,
SCH.MAY,
SCH.JUN,
SCH.JUL,
SCH.AUG,
SCH.SEP,
SCH.OCT,
SCH.NOV,
SCH.DEC,
SCH.JAN_NXT,
SCH.FEB_NXT,
SCH.MAR_NXT,
SCH.APR_NXT,
SCH.MAY_NXT,
SCH.JUN_NXT,
SCH.JUL_NXT,
SCH.AUG_NXT,
SCH.SEP_NXT,
SCH.OCT_NXT,
SCH.NOV_NXT,
SCH.DEC_NXT,
NVL((SELECT
SUM(POLLOC.QUANTITY - POLLOC.QUANTITY_RECEIVED)
FROM
APPS.PO_LINES_ALL POL,
APPS.PO_LINE_LOCATIONS_ALL POLLOC,
APPS.PO_HEADERS_ALL POH
WHERE
POH.PO_HEADER_ID = POL.PO_HEADER_ID
AND POL.PO_LINE_ID = POLLOC.PO_LINE_ID
--AND POLLOC.PO_RELEASE_ID Is Not Null
AND (POLLOC.QUANTITY - POLLOC.QUANTITY_RECEIVED) - POLLOC.QUANTITY_CANCELLED > 0
AND (NVL(POH.CANCEL_FLAG,'N') <> 'Y')
AND (NVL(POL.CANCEL_FLAG,'N') <> 'Y')
AND (NVL(POLLOC.CANCEL_FLAG,'N') <> 'Y')
AND (NVL(POL.CLOSED_CODE,'OPEN') NOT LIKE '%CLOSED%')
AND (NVL(POH.CLOSED_CODE,'OPEN') NOT LIKE '%CLOSED%')
AND (NVL(POLLOC.CLOSED_CODE,'OPEN') NOT IN ('FINALLY CLOSED','CLOSED','CLOSED FOR RECEIVING'/*,'CLOSED FOR INVOICE'*/))
AND POLLOC.SHIPMENT_TYPE <> 'PRICE BREAK'
--AND POLLOC.SHIP_TO_ORGANIZATION_ID = '6162'
AND POLLOC.SHIP_TO_ORGANIZATION_ID = SCH.ORGANIZATION_ID
AND POL.ITEM_ID = SCH.INVENTORY_ITEM_ID
AND POH.VENDOR_ID = SCH.SOURCE_VENDOR_ID),0) OPEN_PO,
SCH.ORGANIZATION_ID,
SCH.INVENTORY_ITEM_ID,
SCH.SUPPLIER_PART_NUMBER
FROM



(SELECT
PV.VENDOR_NAME,
MSI.SEGMENT1 ITEM,
MSI.DESCRIPTION DESCR,
MSI.FULL_LEAD_TIME,
MR.SOURCE_ORGANIZATION_ID,
MR.COMPILE_DESIGNATOR PLAN_NAME,
DECODE(MR.ORDER_TYPE,1,'PO',2,'REQ',5,'PLN','MISSING') ORDER_TYPE,
SUBSTR(ORG.NAME,1,3) ORG_CODE,
ORG.NAME ORG_NAME,
ORG.ORGANIZATION_ID,
MR.SOURCE_VENDOR_ID,
MSI.INVENTORY_ITEM_ID,
Max((SELECT pla.vendor_product_num FROM apps.po_headers_all pha, apps.po_lines_all pla WHERE pha.po_header_id = pla.po_header_id AND pha.type_lookup_code = 'BLANKET' AND pha.AUTHORIZATION_STATUS = 'APPROVED' AND (pla.cancel_flag IS NOT NULL OR pla.cancel_flag = 'N') AND (pha.closed_code IS NULL OR pha.closed_code <> 'CLOSED') AND pla.item_id = msi.inventory_item_id AND RowNum =1)) As Supplier_Part_Number,

-- CURRENT WEEKS VALUES

NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'WWYY'),TO_CHAR(SYSDATE,'WW')||TO_CHAR(SYSDATE,'YY'),MR.NEW_ORDER_QUANTITY)),0) PRESENT_WK,

-- BREAKDOWN FOR THE NEXT 9 WEEKS

NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'WWYY'),(CASE WHEN TO_CHAR(SYSDATE,'WW')+1 >53 THEN '0' WHEN TO_CHAR(SYSDATE,'WW')+1 <10 THEN '0' END) || (CASE WHEN TO_CHAR(SYSDATE,'WW')+1 >53 THEN (TO_CHAR(SYSDATE,'WW')+1)-53 ELSE TO_CHAR(SYSDATE,'WW')+1 END) || (CASE WHEN TO_CHAR(SYSDATE,'WW')+1 >53 THEN TO_CHAR(SYSDATE + 365,'YY') ELSE TO_CHAR(SYSDATE,'YY') END),MR.NEW_ORDER_QUANTITY)),0) PRESENT_WK_1,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'WWYY'),(CASE WHEN TO_CHAR(SYSDATE,'WW')+2 >53 THEN '0' WHEN TO_CHAR(SYSDATE,'WW')+2 <10 THEN '0' END) || (CASE WHEN TO_CHAR(SYSDATE,'WW')+2 >53 THEN (TO_CHAR(SYSDATE,'WW')+2)-53 ELSE TO_CHAR(SYSDATE,'WW')+2 END) || (CASE WHEN TO_CHAR(SYSDATE,'WW')+2 >53 THEN TO_CHAR(SYSDATE + 365,'YY') ELSE TO_CHAR(SYSDATE,'YY') END),MR.NEW_ORDER_QUANTITY)),0) PRESENT_WK_2,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'WWYY'),(CASE WHEN TO_CHAR(SYSDATE,'WW')+3 >53 THEN '0' WHEN TO_CHAR(SYSDATE,'WW')+3 <10 THEN '0' END) || (CASE WHEN TO_CHAR(SYSDATE,'WW')+3 >53 THEN (TO_CHAR(SYSDATE,'WW')+3)-53 ELSE TO_CHAR(SYSDATE,'WW')+3 END) || (CASE WHEN TO_CHAR(SYSDATE,'WW')+3 >53 THEN TO_CHAR(SYSDATE + 365,'YY') ELSE TO_CHAR(SYSDATE,'YY') END),MR.NEW_ORDER_QUANTITY)),0) PRESENT_WK_3,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'WWYY'),(CASE WHEN TO_CHAR(SYSDATE,'WW')+4 >53 THEN '0' WHEN TO_CHAR(SYSDATE,'WW')+4 <10 THEN '0' END) || (CASE WHEN TO_CHAR(SYSDATE,'WW')+4 >53 THEN (TO_CHAR(SYSDATE,'WW')+4)-53 ELSE TO_CHAR(SYSDATE,'WW')+4 END) || (CASE WHEN TO_CHAR(SYSDATE,'WW')+4 >53 THEN TO_CHAR(SYSDATE + 365,'YY') ELSE TO_CHAR(SYSDATE,'YY') END),MR.NEW_ORDER_QUANTITY)),0) PRESENT_WK_4,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'WWYY'),(CASE WHEN TO_CHAR(SYSDATE,'WW')+5 >53 THEN '0' WHEN TO_CHAR(SYSDATE,'WW')+5 <10 THEN '0' END) || (CASE WHEN TO_CHAR(SYSDATE,'WW')+5 >53 THEN (TO_CHAR(SYSDATE,'WW')+5)-53 ELSE TO_CHAR(SYSDATE,'WW')+5 END) || (CASE WHEN TO_CHAR(SYSDATE,'WW')+5 >53 THEN TO_CHAR(SYSDATE + 365,'YY') ELSE TO_CHAR(SYSDATE,'YY') END),MR.NEW_ORDER_QUANTITY)),0) PRESENT_WK_5,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'WWYY'),(CASE WHEN TO_CHAR(SYSDATE,'WW')+6 >53 THEN '0' WHEN TO_CHAR(SYSDATE,'WW')+6 <10 THEN '0' END) || (CASE WHEN TO_CHAR(SYSDATE,'WW')+6 >53 THEN (TO_CHAR(SYSDATE,'WW')+6)-53 ELSE TO_CHAR(SYSDATE,'WW')+6 END) || (CASE WHEN TO_CHAR(SYSDATE,'WW')+6 >53 THEN TO_CHAR(SYSDATE + 365,'YY') ELSE TO_CHAR(SYSDATE,'YY') END),MR.NEW_ORDER_QUANTITY)),0) PRESENT_WK_6,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'WWYY'),(CASE WHEN TO_CHAR(SYSDATE,'WW')+7 >53 THEN '0' WHEN TO_CHAR(SYSDATE,'WW')+7 <10 THEN '0' END) || (CASE WHEN TO_CHAR(SYSDATE,'WW')+7 >53 THEN (TO_CHAR(SYSDATE,'WW')+7)-53 ELSE TO_CHAR(SYSDATE,'WW')+7 END) || (CASE WHEN TO_CHAR(SYSDATE,'WW')+7 >53 THEN TO_CHAR(SYSDATE + 365,'YY') ELSE TO_CHAR(SYSDATE,'YY') END),MR.NEW_ORDER_QUANTITY)),0) PRESENT_WK_7,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'WWYY'),(CASE WHEN TO_CHAR(SYSDATE,'WW')+8 >53 THEN '0' WHEN TO_CHAR(SYSDATE,'WW')+8 <10 THEN '0' END) || (CASE WHEN TO_CHAR(SYSDATE,'WW')+8 >53 THEN (TO_CHAR(SYSDATE,'WW')+8)-53 ELSE TO_CHAR(SYSDATE,'WW')+8 END) || (CASE WHEN TO_CHAR(SYSDATE,'WW')+8 >53 THEN TO_CHAR(SYSDATE + 365,'YY') ELSE TO_CHAR(SYSDATE,'YY') END),MR.NEW_ORDER_QUANTITY)),0) PRESENT_WK_8,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'WWYY'),(CASE WHEN TO_CHAR(SYSDATE,'WW')+9 >53 THEN '0' WHEN TO_CHAR(SYSDATE,'WW')+9 <10 THEN '0' END) || (CASE WHEN TO_CHAR(SYSDATE,'WW')+9 >53 THEN (TO_CHAR(SYSDATE,'WW')+9)-53 ELSE TO_CHAR(SYSDATE,'WW')+9 END) || (CASE WHEN TO_CHAR(SYSDATE,'WW')+9 >53 THEN TO_CHAR(SYSDATE + 365,'YY') ELSE TO_CHAR(SYSDATE,'YY') END),MR.NEW_ORDER_QUANTITY)),0) PRESENT_WK_9,

--FIGURES FOR THE CURRENT YEAR

NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'JAN-'||TO_CHAR(SYSDATE,'YY'),MR.NEW_ORDER_QUANTITY)),0) JAN,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'FEB-'||TO_CHAR(SYSDATE,'YY'),MR.NEW_ORDER_QUANTITY)),0) FEB,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'MAR-'||TO_CHAR(SYSDATE,'YY'),MR.NEW_ORDER_QUANTITY)),0) MAR,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'APR-'||TO_CHAR(SYSDATE,'YY'),MR.NEW_ORDER_QUANTITY)),0) APR,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'MAY-'||TO_CHAR(SYSDATE,'YY'),MR.NEW_ORDER_QUANTITY)),0) MAY,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'JUN-'||TO_CHAR(SYSDATE,'YY'),MR.NEW_ORDER_QUANTITY)),0) JUN,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'JUL-'||TO_CHAR(SYSDATE,'YY'),MR.NEW_ORDER_QUANTITY)),0) JUL,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'AUG-'||TO_CHAR(SYSDATE,'YY'),MR.NEW_ORDER_QUANTITY)),0) AUG,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'SEP-'||TO_CHAR(SYSDATE,'YY'),MR.NEW_ORDER_QUANTITY)),0) SEP,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'OCT-'||TO_CHAR(SYSDATE,'YY'),MR.NEW_ORDER_QUANTITY)),0) OCT,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'NOV-'||TO_CHAR(SYSDATE,'YY'),MR.NEW_ORDER_QUANTITY)),0) NOV,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'DEC-'||TO_CHAR(SYSDATE,'YY'),MR.NEW_ORDER_QUANTITY)),0) DEC,

-- NEXT YEARS FIGURES

NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'JAN-'||TO_CHAR(SYSDATE + 365,'YY'),MR.NEW_ORDER_QUANTITY)),0) JAN_NXT,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'FEB-'||TO_CHAR(SYSDATE + 365,'YY'),MR.NEW_ORDER_QUANTITY)),0) FEB_NXT,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'MAR-'||TO_CHAR(SYSDATE + 365,'YY'),MR.NEW_ORDER_QUANTITY)),0) MAR_NXT,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'APR-'||TO_CHAR(SYSDATE + 365,'YY'),MR.NEW_ORDER_QUANTITY)),0) APR_NXT,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'MAY-'||TO_CHAR(SYSDATE + 365,'YY'),MR.NEW_ORDER_QUANTITY)),0) MAY_NXT,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'JUN-'||TO_CHAR(SYSDATE + 365,'YY'),MR.NEW_ORDER_QUANTITY)),0) JUN_NXT,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'JUL-'||TO_CHAR(SYSDATE + 365,'YY'),MR.NEW_ORDER_QUANTITY)),0) JUL_NXT,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'AUG-'||TO_CHAR(SYSDATE + 365,'YY'),MR.NEW_ORDER_QUANTITY)),0) AUG_NXT,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'SEP-'||TO_CHAR(SYSDATE + 365,'YY'),MR.NEW_ORDER_QUANTITY)),0) SEP_NXT,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'OCT-'||TO_CHAR(SYSDATE + 365,'YY'),MR.NEW_ORDER_QUANTITY)),0) OCT_NXT,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'NOV-'||TO_CHAR(SYSDATE + 365,'YY'),MR.NEW_ORDER_QUANTITY)),0) NOV_NXT,
NVL(SUM(DECODE(TO_CHAR(MR.NEW_SCHEDULE_DATE,'MON-YY'),'DEC-'||TO_CHAR(SYSDATE + 365,'YY'),MR.NEW_ORDER_QUANTITY)),0) DEC_NXT
FROM
APPS.MRP_RECOMMENDATIONS MR,
APPS.MTL_SYSTEM_ITEMS_B MSI,
APPS.AP_SUPPLIERS PV,
APPS.HR_ALL_ORGANIZATION_UNITS ORG


WHERE
1=1
--AND MSI.ORGANIZATION_ID = 6162
AND ORG.ORGANIZATION_ID = MSI.ORGANIZATION_ID
AND ORG.ORGANIZATION_ID = MR.ORGANIZATION_ID
-- AND MSI.PLANNING_MAKE_BUY_CODE = 2
-- AND MSI.PURCHASING_ENABLED_FLAG = 'Y'
AND MSI.INVENTORY_ITEM_ID = MR.INVENTORY_ITEM_ID
AND MR.COMPILE_DESIGNATOR = (CASE
WHEN SUBSTR(ORG.NAME,1,3) IN ('321', '322', '323', '331', '332', '333') THEN 'UK_SCP'
WHEN SUBSTR(ORG.NAME,1,3) IN ('708', '709','719','729') THEN 'CH_SCP'
WHEN SUBSTR(ORG.NAME,1,3) IN ('400', '401','402') THEN 'IN_SCP'
WHEN SUBSTR(ORG.NAME,1,3) IN ('041','014') THEN 'US_SCP'
ELSE MR.COMPILE_DESIGNATOR
END)
AND MR.ORDER_TYPE IN (1,2,5)
AND (MR.NEW_SCHEDULE_DATE BETWEEN SYSDATE AND TO_DATE('31-DEC-'||TO_CHAR(SYSDATE + 365,'YY'),'DD-MON-YY') OR MR.NEW_SCHEDULE_DATE IS NULL)
AND MR.SOURCE_VENDOR_ID = PV.VENDOR_ID (+)
AND SUBSTR(ORG.NAME,1,3) = '341' --'{?Org}'
AND PV.VENDOR_NAME = 'F.A.R FOUNDRY SPA'
-- AND SUBSTR(ORG.NAME,1,3) = '719'

GROUP BY PV.VENDOR_NAME, MSI.FULL_LEAD_TIME, MSI.SEGMENT1, MSI.DESCRIPTION, MR.COMPILE_DESIGNATOR, MR.ORDER_TYPE, ORG.NAME, ORG.ORGANIZATION_ID, MR.SOURCE_VENDOR_ID, MSI.INVENTORY_ITEM_ID,MR.SOURCE_ORGANIZATION_ID) SCH
ORDER BY
SCH.VENDOR_NAME,SCH.ITEM